### ISSUE TITLE
Specinfra failed os detection for suse11 only

### ISSUE THREAD

**Issue by tal5ab** [vvchik/vagrant-serverspec#33]
Hi
We build many types of OS machines
We upgraded lately to vagrant 1.9.1 and 1.9.3
Till then all our tests where ok , but now we got a new failure only for the SUSE11 image
all the tests fails , seems like because it fails to identify the OS

Anyone seen this before? 

C:\tests\DevOps>vagrant plugin list
vagrant-aws (0.6.0)
  - Version Constraint: 0.6.0
vagrant-omnibus (1.5.0)
  - Version Constraint: 1.5.0
vagrant-serverspec (1.1.1)
  - Version Constraint: 1.1.1
vagrant-share (1.1.6, system)
vagrant-winrm-syncedfolders (1.0.1)
  - Version Constraint: 1.0.1
winrm-fs (0.3.2)
  - Version Constraint: 0.3.2

Failures:
```

  1) File "/home/vagrant/stdout/get_params.bat" content 
     On host `35.158.82.159'
     Failure/Error: its(:content) { should match /aws_suse11_trial_v8_pg/ }
     NotImplementedError:
       Specinfra failed os detection.
       /bin/sh -c uname\ -s
       Linux

     # C:/Users/tabramso/.vagrant.d/gems/2.2.5/gems/specinfra-2.67.6/lib/specinfra/helper/os.rb:30:in `detect_os'
     # C:/Users/tabramso/.vagrant.d/gems/2.2.5/gems/specinfra-2.67.6/lib/specinfra/helper/os.rb:9:in `os'
     # C:/Users/tabramso/.vagrant.d/gems/2.2.5/gems/specinfra-2.67.6/lib/specinfra/runner.rb:7:in `method_missing'
     # C:/Users/tabramso/.vagrant.d/gems/2.2.5/gems/serverspec-2.38.0/lib/serverspec/type/file.rb:113:in `content'
     # ./kitchen/spec/Tests_spec.rb:4:in `block (2 levels) in <top (required)>'
     # C:/Users/tabramso/.vagrant.d/gems/2.2.5/gems/vagrant-serverspec-1.1.1/lib/vagrant-serverspec/provisioner.rb:66:in `provision'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/provision.rb:133:in `run_provisioner'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:95:in `call'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:479:in `hook'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/provision.rb:121:in `call'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/provision.rb:121:in `block in call'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/provision.rb:103:in `each'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/provision.rb:103:in `call'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/call.rb:53:in `call'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:225:in `action_raw'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:200:in `block in action'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:567:in `lock'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `call'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `action'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/provision/command.rb:30:in `block in execute'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/v2/command.rb:235:in `block in with_target_vms'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/v2/command.rb:229:in `each'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/v2/command.rb:229:in `with_target_vms'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/provision/command.rb:29:in `execute'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/cli.rb:42:in `execute'
     # C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:308:in `cli'

Finished in 6.93 seconds (files took 0.10059 seconds to load)
1 example, 1 failure
```

**Comment by tal5ab** [comment]
Ok , i found they where touching the suse part of os detect on this module:
https://github.com/mizzy/specinfra/commits/master/lib/specinfra/helper/detect_os/suse.rb

So i might got this bug from there

How do i tell vagrant to get the newer code , or go back to older code of a specific helper gem ?
